BERT_PRETRAINED_PATH = "bert-base-uncased"
CLIP_PRETRAINED_PATH = "openai/clip-vit-base-patch32"
LXMERT_PRETRAINED_PATH = "unc-nlp/lxmert-base-uncased"
ResNet_PRETRAINED_PATH = "microsoft/resnet-50"
RoBERTa_PRETRAINED_PATH = "roberta-base"
Electra_PRETRAINED_PATH = "google/electra-base-discriminator"
ViLT_PRETRAINED_PATH = "dandelin/vilt-b32-mlm"
ViT_PRETRAINED_PATH = "google/vit-base-patch16-224"
